name: Download disposable email domains

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

permissions:
  contents: write

jobs:
  download-lists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Run script to fetch domains
        run: node .

      - name: Commit and push if changed
        run: |
          git config user.name "Sefinek Actions"
          git config user.email "sefinek.actions@gmail.com"
          git add blacklist.txt
          git commit -m "✨ Update disposable email domains" || echo "No changes to commit"
          git push
